@startuml

title GraphTool

class GraphHandler{
  -datalist : List<data>

  ..For Drawer..
  +OnUpdateGraph : Action
  +ScopeRect : Rect
  +GridScale : Vector2
  +GridSubdivisionX,Y : int
  +GridAutoScalingThreshold : int
  +IEnumerator<float> GetDataEnumerator(int)

  ..For External Script..
  +bool HasData(int)
  +float? GetCurrentData(key)
  +void SetData(int, float)
  +void UpdateGraph()
  +void Determine()
  +void Clear()
  +void ToggleRecording()

}

class GraphPartsBase <<abstract>>
class PlotterBase <<abstract>>
class Plotter
class Grid
class Data{
  +name : string
  #data : List<float?>
  #currentData : float?
  +float? GetCurrent()
  +void SetCurrent(float)
  +void Determine()
  +IEnumerator<value?> GetEnumerator()
  +void Clear()
}

GraphPartsBase <|.. Grid
GraphPartsBase <|.. PlotterBase
PlotterBase <|.. Plotter
GraphPartsBase .> GraphHandler
PlotterBase ..> GraphHandler
GraphHandler "1" o- "0..*" Data

@enduml
