@startuml
title Search Recorder
(*) --> input
input --> has property name?
if propName != null then
 ->[false] "GetObject('scope')" as GetObjByConstScope
else
 -->[true] GetObject(propName)
if obj.Type == Scope then
 ->[true] return GetRecorderObj
else
 -->[false] "is Recorder" as IsRecorder

 if obj.Type == Recorder then
  -l->[true] return obj
else
 -->[false] return error

GetObjByConstScope --> "is Scope?" as IsScope
if obj.Type == Scope then
 ->[false] "GetObject('recorder')" as GetObjByConstRecorder
else
 -->[true] return GetRecorderObj

@enduml
